/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unifio.segundo.projeto;

import javax.swing.JOptionPane;

/**
 *
 * @author Delfino
 */
public class SegundaTela extends javax.swing.JFrame {

    /**
     * Creates new form SegundaTela
     */
    public SegundaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPremio = new javax.swing.ButtonGroup();
        lbPremio = new javax.swing.JLabel();
        radCasa = new javax.swing.JRadioButton();
        radCarro = new javax.swing.JRadioButton();
        radBarco = new javax.swing.JRadioButton();
        btPremio = new javax.swing.JButton();
        lbInteresses = new javax.swing.JLabel();
        chkViagens = new javax.swing.JCheckBox();
        chkCinema = new javax.swing.JCheckBox();
        chkLivros = new javax.swing.JCheckBox();
        chkJogos = new javax.swing.JCheckBox();
        btInteresses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPremio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbPremio.setText("Escolha o seu prêmio");

        groupPremio.add(radCasa);
        radCasa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radCasa.setText("Casa");

        groupPremio.add(radCarro);
        radCarro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radCarro.setText("Carro");

        groupPremio.add(radBarco);
        radBarco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radBarco.setSelected(true);
        radBarco.setText("Barco");

        btPremio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btPremio.setText("Prêmio");
        btPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPremioActionPerformed(evt);
            }
        });

        lbInteresses.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbInteresses.setText("Marque os seus interesses");

        chkViagens.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        chkViagens.setText("Viagens");

        chkCinema.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        chkCinema.setText("Cinema");

        chkLivros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        chkLivros.setText("Livros");

        chkJogos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        chkJogos.setText("Jogos");

        btInteresses.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btInteresses.setText("Interesses");
        btInteresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInteressesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPremio)
                    .addComponent(radCasa)
                    .addComponent(radCarro)
                    .addComponent(radBarco)
                    .addComponent(btPremio))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInteresses)
                    .addComponent(chkViagens)
                    .addComponent(lbInteresses)
                    .addComponent(chkCinema)
                    .addComponent(chkJogos)
                    .addComponent(chkLivros))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPremio)
                    .addComponent(lbInteresses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCasa)
                    .addComponent(chkViagens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCarro)
                    .addComponent(chkCinema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPremio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkLivros)
                        .addGap(18, 18, 18)
                        .addComponent(chkJogos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInteresses)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPremioActionPerformed
        if (radCasa.isSelected()) {
            JOptionPane.showMessageDialog(null, "Você escolheu a casa");
        } else if (radCarro.isSelected()) {
            JOptionPane.showMessageDialog(null, "Você escolheu o carro");
        } else {
            JOptionPane.showMessageDialog(null, "Você escolheu o barco");
        }
    }//GEN-LAST:event_btPremioActionPerformed

    private void btInteressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInteressesActionPerformed
        String opcoes = "";
        
        if (chkViagens.isSelected()) {
            opcoes += "Viagens\n";
        }
        
        if (chkCinema.isSelected()) {
            opcoes += "Cinema\n";
        }
        
        if (chkLivros.isSelected()) {
            opcoes += "Livros\n";
        }
        
        if (chkJogos.isSelected()) {
            opcoes += "Jogos\n";
        }
        
        if (opcoes.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Você não escolheu nenhuma opção"); 
        } else {
            JOptionPane.showMessageDialog(null, "Você escolheu as opções\n" + opcoes);
        }
    }//GEN-LAST:event_btInteressesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInteresses;
    private javax.swing.JButton btPremio;
    private javax.swing.JCheckBox chkCinema;
    private javax.swing.JCheckBox chkJogos;
    private javax.swing.JCheckBox chkLivros;
    private javax.swing.JCheckBox chkViagens;
    private javax.swing.ButtonGroup groupPremio;
    private javax.swing.JLabel lbInteresses;
    private javax.swing.JLabel lbPremio;
    private javax.swing.JRadioButton radBarco;
    private javax.swing.JRadioButton radCarro;
    private javax.swing.JRadioButton radCasa;
    // End of variables declaration//GEN-END:variables
}
